CREATE TABLE public.users(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  location text NOT NULL,
  rating numeric DEFAULT 0 NOT NULL,
  total_reviews integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.coins(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  origin text NOT NULL,
  year text NOT NULL,
  material text NOT NULL,
  condition text NOT NULL,
  description text NOT NULL,
  photos jsonb DEFAULT '[]'::jsonb NOT NULL,
  available_for_sale boolean DEFAULT FALSE NOT NULL,
  available_for_trade boolean DEFAULT FALSE NOT NULL,
  price numeric,
  trade_preference text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.conversations(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id bigint NOT NULL REFERENCES public.coins(id) ON DELETE CASCADE,
  buyer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  seller_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status text DEFAULT 'aberta' NOT NULL,
  messages jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.reviews(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  reviewer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reviewed_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stars integer NOT NULL,
  comment text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX conversations_unique_open_negotiation ON public.conversations(coin_id, buyer_id, seller_id)
WHERE
  status = 'aberta';

CREATE UNIQUE INDEX reviews_unique_per_conversation_reviewer ON public.reviews(conversation_id, reviewer_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
BEGIN
  INSERT INTO public.users(auth_id, name, email, location)
    VALUES(NEW.id, COALESCE(NEW.raw_user_meta_data ->> 'name', split_part(NEW.email, '@', 1)), NEW.email, COALESCE(NEW.raw_user_meta_data ->> 'location', 'Por definir'))
  ON CONFLICT(auth_id)
    DO NOTHING;
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.update_user_rating_from_reviews()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
DECLARE
  target_user_id bigint;
BEGIN
  target_user_id := COALESCE(NEW.reviewed_user_id, OLD.reviewed_user_id);
  UPDATE
    public.users
  SET
    rating = COALESCE((
      SELECT
        round(avg(stars)::numeric, 1)
      FROM public.reviews
      WHERE
        reviewed_user_id = target_user_id), 0), total_reviews =(
      SELECT
        count(*)
      FROM
        public.reviews
      WHERE
        reviewed_user_id = target_user_id)
  WHERE
    id = target_user_id;
  RETURN COALESCE(new, old);
END;
$$;

CREATE TRIGGER on_review_changed
  AFTER INSERT OR UPDATE OR DELETE ON public.reviews
  FOR EACH ROW
  EXECUTE FUNCTION public.update_user_rating_from_reviews();

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.coins ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Utilizadores autenticados podem ler perfis" ON public.users
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "Utilizador cria o proprio perfil" ON public.users
  FOR INSERT TO authenticated
  WITH CHECK (auth_id = auth.uid());

CREATE POLICY "Utilizador atualiza o proprio perfil" ON public.users
  FOR UPDATE TO authenticated
  USING (auth_id = auth.uid())
  WITH CHECK (auth_id = auth.uid());

CREATE POLICY "Utilizadores autenticados podem ler moedas" ON public.coins
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "Utilizador cria moedas proprias" ON public.coins
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Utilizador atualiza moedas proprias" ON public.coins
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Utilizador remove moedas proprias" ON public.coins
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Participantes podem ler conversas" ON public.conversations
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)));

CREATE POLICY "Comprador cria conversa propria" ON public.conversations
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = conversations.buyer_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Participantes atualizam conversas" ON public.conversations
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)));

CREATE POLICY "Utilizadores autenticados podem ler reviews" ON public.reviews
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "Utilizador cria reviews proprias" ON public.reviews
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Utilizador atualiza reviews proprias" ON public.reviews
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()));

GRANT usage ON SCHEMA public TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.users TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.coins TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.conversations TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.reviews TO authenticated;

GRANT usage, SELECT ON ALL sequences IN SCHEMA public TO authenticated;

CREATE POLICY "Todos podem ver imagens das moedas" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'coin-images');

CREATE POLICY "Utilizadores autenticados enviam imagens das moedas" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'coin-images');

CREATE POLICY "Utilizadores autenticados atualizam imagens das moedas" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'coin-images')
  WITH CHECK (bucket_id = 'coin-images');

CREATE POLICY "Utilizadores autenticados removem imagens das moedas" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'coin-images');

