-- ============================================================
-- 0. RESET DA BASE DE DADOS
-- ============================================================

-- Remove as policies externas.
DROP POLICY IF EXISTS "Todos podem ver imagens das moedas" ON storage.objects;
DROP POLICY IF EXISTS "Utilizadores autenticados enviam imagens das moedas" ON storage.objects;
DROP POLICY IF EXISTS "Utilizadores autenticados atualizam imagens das moedas" ON storage.objects;
DROP POLICY IF EXISTS "Utilizadores autenticados removem imagens das moedas" ON storage.objects;

-- Remove o trigger ligado a auth.users antes de remover a sua funcao.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Retira a propriedade dos ficheiros e buckets para permitir eliminar todos os utilizadores, sem apagar as imagens guardadas no Storage.
UPDATE storage.objects
SET owner_id = NULL
WHERE owner_id IS NOT NULL;

UPDATE storage.buckets
SET owner_id = NULL
WHERE owner_id IS NOT NULL;

-- Remove todas as contas do Supabase Auth.
DELETE FROM auth.users;

-- Remove as tabelas pela ordem das suas dependencias.
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.conversations CASCADE;
DROP TABLE IF EXISTS public.coins CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- Remove as funcoes usadas pelos triggers.
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP FUNCTION IF EXISTS public.update_user_rating_from_reviews();


-- ============================================================
-- 1. TABELAS PRINCIPAIS
-- ============================================================

-- Perfis publicos dos utilizadores da aplicacao.
-- auth_id liga este perfil ao utilizador criado pelo Supabase Auth.
-- rating e total_reviews sao atualizados automaticamente por um trigger.
CREATE TABLE public.users(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  location text NOT NULL,
  rating numeric DEFAULT 0 NOT NULL,
  total_reviews integer DEFAULT 0 NOT NULL
);

-- Moedas adicionadas pelos utilizadores.
-- photos guarda uma lista de URLs em formato JSON.
CREATE TABLE public.coins(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  origin text NOT NULL,
  year text NOT NULL,
  material text NOT NULL,
  condition text NOT NULL,
  description text NOT NULL,
  photos jsonb DEFAULT '[]'::jsonb NOT NULL,
  available_for_sale boolean DEFAULT FALSE NOT NULL,
  available_for_trade boolean DEFAULT FALSE NOT NULL,
  price numeric,
  trade_preference text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Conversas/negociacoes entre um comprador e um vendedor.
-- As mensagens sao guardadas como uma lista JSON no campo messages.
CREATE TABLE public.conversations(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id bigint NOT NULL REFERENCES public.coins(id) ON DELETE CASCADE,
  buyer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  seller_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status text DEFAULT 'aberta' NOT NULL,
  messages jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Avaliacoes feitas no contexto de uma conversa.
-- reviewer_id identifica quem avaliou.
-- reviewed_user_id identifica quem recebeu a avaliacao.
CREATE TABLE public.reviews(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  reviewer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reviewed_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stars integer NOT NULL,
  comment text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);


-- ============================================================
-- 2. INDICES E RESTRICOES DE UNICIDADE
-- ============================================================

-- Impede que exista mais do que uma negociacao aberta para a mesma moeda, com o mesmo comprador e vendedor.
CREATE UNIQUE INDEX conversations_unique_open_negotiation ON public.conversations(coin_id, buyer_id, seller_id)
WHERE
  status = 'aberta';

-- Cada utilizador so pode fazer uma avaliacao por conversa.
CREATE UNIQUE INDEX reviews_unique_per_conversation_reviewer ON public.reviews(conversation_id, reviewer_id);


-- ============================================================
-- 3. CRIACAO AUTOMATICA DO PERFIL DO UTILIZADOR
-- ============================================================

-- Funcao executada quando uma conta e criada no Supabase Auth.
-- SECURITY DEFINER faz a funcao usar as permissoes de quem a criou, permitindo inserir o perfil mesmo com RLS ativa.
CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
BEGIN
  -- NEW representa o novo registo criado na tabela auth.users.
  INSERT INTO public.users(auth_id, name, email, location)
    VALUES(NEW.id, COALESCE(NEW.raw_user_meta_data ->> 'name', split_part(NEW.email, '@', 1)), NEW.email, COALESCE(NEW.raw_user_meta_data ->> 'location', 'Por definir'))
  ON CONFLICT(auth_id)
    DO NOTHING;
  RETURN new;
END;
$$;

-- Depois de inserir uma conta em auth.users, cria o perfil em public.users.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- 4. ATUALIZACAO AUTOMATICA DAS AVALIACOES
-- ============================================================

-- Recalcula o rating medio e o numero de reviews do utilizador avaliado.
CREATE OR REPLACE FUNCTION public.update_user_rating_from_reviews()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
DECLARE
  target_user_id bigint;
BEGIN
  -- NEW existe num INSERT/UPDATE e OLD existe num DELETE.
  -- COALESCE escolhe o valor que estiver disponivel.
  target_user_id := COALESCE(NEW.reviewed_user_id, OLD.reviewed_user_id);
  UPDATE
    public.users
  SET
    rating = COALESCE((
      SELECT
        round(avg(stars)::numeric, 1)
      FROM public.reviews
      WHERE
        reviewed_user_id = target_user_id), 0), total_reviews =(
      SELECT
        count(*)
      FROM
        public.reviews
      WHERE
        reviewed_user_id = target_user_id)
  WHERE
    id = target_user_id;
  RETURN COALESCE(new, old);
END;
$$;

-- Executa a funcao sempre que uma review e criada, editada ou eliminada.
CREATE TRIGGER on_review_changed
  AFTER INSERT OR UPDATE OR DELETE ON public.reviews
  FOR EACH ROW
  EXECUTE FUNCTION public.update_user_rating_from_reviews();


-- ============================================================
-- 5. ROW LEVEL SECURITY (RLS)
-- ============================================================
-- Ativar RLS faz com que o acesso as linhas seja controlado pelas policies definidas abaixo.

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.coins ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 6. POLICIES DOS UTILIZADORES
-- ============================================================

-- Todos os utilizadores autenticados podem consultar perfis.
CREATE POLICY "Utilizadores autenticados podem ler perfis" ON public.users
  FOR SELECT TO authenticated
  USING (TRUE);

-- Um utilizador so pode criar um perfil associado a sua conta Auth.
CREATE POLICY "Utilizador cria o proprio perfil" ON public.users
  FOR INSERT TO authenticated
  WITH CHECK (auth_id = auth.uid());

-- USING controla quais linhas existentes podem ser atualizadas.
-- WITH CHECK valida como a linha pode ficar depois da atualizacao.
CREATE POLICY "Utilizador atualiza o proprio perfil" ON public.users
  FOR UPDATE TO authenticated
  USING (auth_id = auth.uid())
  WITH CHECK (auth_id = auth.uid());


-- ============================================================
-- 7. POLICIES DAS MOEDAS
-- ============================================================

-- Todos os utilizadores autenticados podem consultar moedas.
CREATE POLICY "Utilizadores autenticados podem ler moedas" ON public.coins
  FOR SELECT TO authenticated
  USING (TRUE);

-- So e possivel criar uma moeda com owner_id igual ao perfil do utilizador atualmente autenticado.
CREATE POLICY "Utilizador cria moedas proprias" ON public.coins
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

-- Apenas o proprietario pode atualizar a moeda.
CREATE POLICY "Utilizador atualiza moedas proprias" ON public.coins
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

-- Apenas o proprietario pode eliminar a moeda.
CREATE POLICY "Utilizador remove moedas proprias" ON public.coins
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));


-- ============================================================
-- 8. POLICIES DAS CONVERSAS
-- ============================================================

-- Apenas o comprador e o vendedor podem consultar a conversa.
CREATE POLICY "Participantes podem ler conversas" ON public.conversations
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)));

-- So o utilizador identificado como comprador pode criar a conversa.
CREATE POLICY "Comprador cria conversa propria" ON public.conversations
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = conversations.buyer_id
      AND users.auth_id = auth.uid()));

-- O comprador e o vendedor podem atualizar a conversa, por exemplo, para adicionar mensagens ou alterar o estado da negociacao.
CREATE POLICY "Participantes atualizam conversas" ON public.conversations
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)));


-- ============================================================
-- 9. POLICIES DAS REVIEWS
-- ============================================================

-- Todos os utilizadores autenticados podem consultar avaliacoes.
CREATE POLICY "Utilizadores autenticados podem ler reviews" ON public.reviews
  FOR SELECT TO authenticated
  USING (TRUE);

-- Um utilizador so pode criar uma review em seu proprio nome.
CREATE POLICY "Utilizador cria reviews proprias" ON public.reviews
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()));

-- Um utilizador so pode atualizar reviews criadas por ele.
CREATE POLICY "Utilizador atualiza reviews proprias" ON public.reviews
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()));


-- ============================================================
-- 10. PERMISSOES PARA UTILIZADORES AUTENTICADOS
-- ============================================================
-- As policies decidem quais linhas podem ser usadas.
-- Os GRANT abaixo decidem quais operacoes SQL podem ser executadas.

GRANT usage ON SCHEMA public TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.users TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.coins TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.conversations TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.reviews TO authenticated;

GRANT usage, SELECT ON ALL sequences IN SCHEMA public TO authenticated;


-- ============================================================
-- 11. POLICIES DO SUPABASE STORAGE
-- ============================================================
-- Estas policies controlam os ficheiros do bucket coin-images.

-- Qualquer pessoa pode visualizar as imagens das moedas.
CREATE POLICY "Todos podem ver imagens das moedas" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'coin-images');

-- Apenas utilizadores autenticados podem enviar imagens.
CREATE POLICY "Utilizadores autenticados enviam imagens das moedas" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'coin-images');

-- Apenas utilizadores autenticados podem atualizar imagens.
CREATE POLICY "Utilizadores autenticados atualizam imagens das moedas" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'coin-images')
  WITH CHECK (bucket_id = 'coin-images');

-- Apenas utilizadores autenticados podem eliminar imagens.
CREATE POLICY "Utilizadores autenticados removem imagens das moedas" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'coin-images');
