CREATE TABLE public.users(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  location text NOT NULL,
  rating numeric DEFAULT 0 NOT NULL,
  total_reviews integer DEFAULT 0 NOT NULL
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users(auth_id, name, email, location, rating, total_reviews)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    COALESCE(new.raw_user_meta_data->>'location', 'Por definir'),
    0,
    0
  )
  ON CONFLICT (auth_id) DO NOTHING;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TABLE public.coins(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  origin text NOT NULL,
  year text NOT NULL,
  material text NOT NULL,
  condition text NOT NULL,
  description text NOT NULL,
  photos jsonb DEFAULT '[]'::jsonb NOT NULL,
  available_for_sale boolean DEFAULT FALSE NOT NULL,
  available_for_trade boolean DEFAULT FALSE NOT NULL,
  price numeric,
  trade_preference text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.conversations(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coin_id bigint NOT NULL REFERENCES public.coins(id) ON DELETE CASCADE,
  buyer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  seller_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status text DEFAULT 'aberta' NOT NULL,
  messages jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.reviews(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  reviewer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reviewed_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  stars integer NOT NULL,
  comment text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.coins ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Utilizadores autenticados podem ler perfis" ON public.users
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "Utilizador cria o proprio perfil" ON public.users
  FOR INSERT TO authenticated
  WITH CHECK (auth_id = auth.uid());

CREATE POLICY "Utilizador atualiza o proprio perfil" ON public.users
  FOR UPDATE TO authenticated
  USING (auth_id = auth.uid())
  WITH CHECK (auth_id = auth.uid());

CREATE POLICY "Utilizadores autenticados podem ler moedas" ON public.coins
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "Utilizador cria moedas proprias" ON public.coins
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Utilizador atualiza moedas proprias" ON public.coins
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Utilizador remove moedas proprias" ON public.coins
  FOR DELETE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = coins.owner_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Participantes podem ler conversas" ON public.conversations
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)));

CREATE POLICY "Comprador cria conversa propria" ON public.conversations
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = conversations.buyer_id
      AND users.auth_id = auth.uid()));

CREATE POLICY "Participantes atualizam conversas" ON public.conversations
  FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)))
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.auth_id = auth.uid()
      AND (users.id = conversations.buyer_id
      OR users.id = conversations.seller_id)));

CREATE POLICY "Utilizadores autenticados podem ler reviews" ON public.reviews
  FOR SELECT TO authenticated
  USING (TRUE);

CREATE POLICY "Utilizador cria reviews proprias" ON public.reviews
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT
      1
    FROM
      public.users
    WHERE
      users.id = reviews.reviewer_id
      AND users.auth_id = auth.uid()));

GRANT usage ON SCHEMA public TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.users TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.coins TO authenticated;

GRANT SELECT, INSERT, UPDATE ON public.conversations TO authenticated;

GRANT SELECT, INSERT ON public.reviews TO authenticated;

GRANT usage, SELECT ON ALL sequences IN SCHEMA public TO authenticated;

INSERT INTO public.users(id, auth_id, name, email, location, rating, total_reviews)
VALUES
  (1, '739f824a-2728-4b48-bb50-0e46122f1dc9', 'Goncalo Sousa', 'goncalo@gmail.com', 'Viana do Castelo', 4.8, 12),
(2, '922430df-9774-43ba-b762-e0d24f535435', 'Miguel Fonseca', 'miguel@gmail.com', 'Viana do Castelo', 4.8, 10),
(3, 'e3f20df3-67ab-4c1b-8a54-4863aa9e80ec', 'Rui Mendonca', 'rui@gmail.com', 'Viana do Castelo', 4.8, 11),
(4, 'ce9d46e9-18e7-45b2-a2e1-47ed9c21f7d5', 'Ricardo Ferreira', 'ricardo@gmail.com', 'Braga', 4.9, 23),
(5, 'c486dc9e-36a2-490e-88ce-a501becbcbab', 'Ana Martins', 'ana@gmail.com', 'Porto', 4.7, 8);

INSERT INTO public.coins(id, owner_id, name, origin, year, material, condition, description, photos, available_for_sale, available_for_trade, price, trade_preference, created_at, updated_at)
VALUES
  (101, 1, '2 Euros Comemorativa Portugal', 'Portugal', '2021', 'Bimetalica', 'Muito Bom', 'Moeda comemorativa portuguesa duplicada na colecao pessoal.', '["assets/img/portugal_coin.jpg"]'::jsonb, FALSE, TRUE, NULL, 'Moedas estrangeiras em bom estado', '2026-05-14T09:30:00.000Z', '2026-05-14T09:30:00.000Z'),
(102, 2, 'Denario de Constantino I', 'Imperio Romano', '310 d.C.', 'Prata', 'Excelente', 'Moeda romana rara em excelente estado de conservacao. Cunhada durante o reinado de Constantino I, apresenta detalhes nitidos.', '["assets/img/constantino.jfif"]'::jsonb, TRUE, FALSE, 450, NULL, '2026-05-15T18:20:00.000Z', '2026-05-15T18:20:00.000Z'),
(103, 3, 'Dobra Portuguesa', 'Portugal', '1724', 'Ouro', 'Bom', 'Moeda antiga portuguesa para apreciadores de numismatica nacional.', '["assets/img/Dobra_Portuguesa.webp"]'::jsonb, TRUE, TRUE, 420, 'Moedas romanas ou gregas', '2026-05-16T14:10:00.000Z', '2026-05-16T14:10:00.000Z');

INSERT INTO public.conversations(id, coin_id, buyer_id, seller_id, status, messages, created_at, updated_at)
  VALUES (201, 102, 1, 2, 'aberta', '[
    {
      "id": 301,
      "sender_id": 1,
      "text": "Boa tarde, ainda tem o denario disponivel?",
      "created_at": "2026-05-17T16:30:00.000Z"
    },
    {
      "id": 302,
      "sender_id": 2,
      "text": "Boa tarde. Sim, ainda esta disponivel.",
      "created_at": "2026-05-17T16:42:00.000Z"
    }
  ]'::jsonb, '2026-05-17T16:30:00.000Z', '2026-05-17T16:42:00.000Z');

SELECT
  setval(pg_get_serial_sequence('public.users', 'id'),(
      SELECT
        max(id)
      FROM public.users));

SELECT
  setval(pg_get_serial_sequence('public.coins', 'id'),(
      SELECT
        max(id)
      FROM public.coins));

SELECT
  setval(pg_get_serial_sequence('public.conversations', 'id'),(
      SELECT
        max(id)
      FROM public.conversations));
